
export const ENCAR_OPTIONS: Record<string, any> = {
    "metas": [
        {
            "key": "01",
            "value": "Exterior/Interior"
        },
        {
            "key": "02",
            "value": "Safety"
        },
        {
            "key": "03",
            "value": "Convenience/Multimedia"
        },
        {
            "key": "04",
            "value": "Seat"
        },
        {
            "key": null,
            "value": null
        }
    ],
    "options": [
        {
            "optionCd": "010",
            "optionName": "Sunroof",
            "optionTypeCd": "01",
            "sort": 1,
            "imagePath": "/carsdata/option_images/option1-1.png",
            "description": "A car roof is made of glass and can be opened and closed. It has a sunroof and a wide panoramic sunroof. There is.",
            "group": false,
            "optionTitle": "Sunroof",
            "groupOptionName": "Sunroof",
            "location": "The roof is made of glass and can be opened and closed. Occasionally, there are glass roofs that do not open and close, but these models can also be considered a type of sunroof.",
            "subOptions": null,
            "icon": "Sun"
        },
        {
            "optionCd": "001",
            "optionName": "Headlamp",
            "optionTypeCd": "01",
            "sort": 2,
            "imagePath": "/carsdata/option_images/option1-2.png",
            "description": "HID/LED headlamps are closer to natural light than general halogen lamps, so they do not strain the eyes and provide a wide range of visibility.",
            "group": true,
            "optionTitle": "Headlamp (HID, LED)",
            "groupOptionName": "Headlamp",
            "location": "HID/LED headlamps are closer to natural light than general halogen lamps. The contrast color is close to natural light, so it does not strain your eyes and has a wide visibility range.",
            "subOptions": [
                {
                    "optionCd": "029",
                    "optionName": "Headlamp (HID)",
                    "optionTypeCd": "01",
                    "sort": 2,
                    "imagePath": "/carsdata/option_images/option1-2.png",
                    "description": "HID/LED headlamps have a color close to natural light, so it does not strain your eyes and has a wide visibility range.",
                    "group": false,
                    "optionTitle": "Headlamp (HID, LED)",
                    "groupOptionName": "Headlamp (HID)",
                    "location": "The color is closer to natural light than a halogen lamp, so it can be confirmed with the naked eye. HID is confirmed by the presence or absence of a ballast, and it is difficult to identify from the outside.\nThere are designs with multiple LEDs instead of just one, and there are also models with a light cover LED logo engraved. Even the high-spec version, Laser, has LED headlamps. Check with options.",
                    "subOptions": null,
                    "icon": "Lightbulb"
                },
                {
                    "optionCd": "075",
                    "optionName": "Headlamp (LED)",
                    "optionTypeCd": "01",
                    "sort": 3,
                    "imagePath": "/carsdata/option_images/option1-2.png",
                    "description": "HID/LED headlamps are closer to natural light than general halogen lamps, so they do not strain the eyes and have a wide visibility range.",
                    "group": false,
                    "optionTitle": "Headlamp (HID, LED)",
                    "groupOptionName": "Headlamp (LED)",
                    "location": "The color is closer to natural light than halogen lamps, so it can be confirmed with the naked eye. HID is confirmed by the presence or absence of a ballast, and it is difficult to identify from the outside.\nThere are designs with multiple LEDs instead of one, and there are also models with a light cover LED logo engraved. The high-spec version, Laser, also has LED headlamps as an option. Check.",
                    "subOptions": null,
                    "icon": "Lightbulb"
                }
            ],
            "icon": "Lightbulb"
        },
        {
            "optionCd": "059",
            "optionName": "Power Electric Trunk",
            "optionTypeCd": "01",
            "sort": 4,
            "imagePath": "/carsdata/option_images/option1-3.png",
            "description": "This is a function that allows you to easily close the trunk with a switch without applying force.",
            "group": false,
            "optionTitle": "Power electric trunk",
            "groupOptionName": "Power electric trunk",
            "location": "The opening switch can be seen with the naked eye around the trunk line.",
            "subOptions": null,
            "icon": "Package"
        },
        {
            "optionCd": "080",
            "optionName": "Ghost door closing",
            "optionTypeCd": "01",
            "sort": 5,
            "imagePath": "/carsdata/option_images/option1-4.png",
            "description": "Also called the electric power door system, it detects when the passenger does not completely close the door, and activates the motor to completely close the door.",
            "group": false,
            "optionTitle": "Ghost door Closing",
            "groupOptionName": "Ghost Door Closing",
            "location": "Even if you do not forcefully close the door completely, it closes smoothly and completely when it is in the state before closing.",
            "subOptions": null,
            "icon": "DoorOpen"
        },
        {
            "optionCd": "024",
            "optionName": "Power folding side mirror",
            "optionTypeCd": "01",
            "sort": 6,
            "imagePath": "/carsdata/option_images/option1-5.png",
            "description": "This is a function that allows you to fold the side mirror with a switch when parking or in a narrow space.",
            "group": false,
            "optionTitle": "Power folding side mirror",
            "groupOptionName": "Power folding side mirror",
            "location": "There is usually a switch around the driver's window switch, and some tuned vehicles fold without a switch. If it has a function that folds and unfolds when you press the switch, or if it satisfies one of the functions of folding and unfolding before and after starting the car, it is an electric folding side mirror. Check.",
            "subOptions": null,
            "icon": "PanelRightOpen"
        },
        {
            "optionCd": "017",
            "optionName": "Aluminum wheel",
            "optionTypeCd": "01",
            "sort": 7,
            "imagePath": "/carsdata/option_images/option1-6.png",
            "description": "It is a wheel made of aluminum alloy and is lighter than a regular steel wheel.",
            "group": false,
            "optionTitle": "Aluminum wheel",
            "groupOptionName": "Aluminum wheel",
            "location": "General steel has a plastic cover on top of the steel, but aluminum wheels do not have a separate cover and are light in weight, which is good for fuel efficiency. To distinguish it from steel wheels,\nvarious types of wheels, such as chrome wheels, are also checked as aluminum wheels. There are two vertically installed rods on the roof of the vehicle to load or secure cargo. These are called roof racks or roof rails.",
            "icon": "CircleDashed",
            "subOptions": null
        },
        {
            "optionCd": "062",
            "optionName": "Roof rack",
            "optionTypeCd": "01",
            "sort": 8,
            "imagePath": "/carsdata/option_images/option1-7.png",
            "description": "A roof rack or roof rail is two vertically installed rods on the roof of the vehicle. You can visually see that there are two vertically installed rails or ... Wheel",
            "icon": "Package",
            "subOptions": null
        },
        {
            "optionCd": "083",
            "optionName": "Power-adjustable steering wheel",
            "optionTypeCd": "01",
            "sort": 10,
            "imagePath": "/carsdata/option_images/option1-9.png",
            "description": "The steering wheel can be tilted and telescopically adjusted to a position that suits the driver.",
            "group": false,
            "optionTitle": "Power-adjustable steering wheel",
            "groupOptionName": "Power-adjustable steering wheel",
            "location": "The steering wheel adjustment switch can be found on the inside of the steering wheel to check the adjustable functions.",
            "subOptions": null,
            "icon": "MoveHorizontal"
        },
        {
            "optionCd": "084",
            "optionName": "Paddle Shift",
            "optionTypeCd": "01",
            "sort": 11,
            "imagePath": "/carsdata/option_images/option1-10.png",
            "description": "A lever or button is mounted near the steering wheel to shift gears, and some electric and hybrid vehicles can adjust the sensitivity of regenerative braking.",
            "group": false,
            "optionTitle": "Paddle shift",
            "groupOptionName": "Paddle shift",
            "location": "Located on the left and right of the steering wheel, there are buttons as well as the standard paddle type.",
            "subOptions": null,
            "icon": "Repeat"
        },
        {
            "optionCd": "031",
            "optionName": "Steering wheel remote control",
            "optionTypeCd": "01",
            "sort": 12,
            "imagePath": "/carsdata/option_images/option1-11.png",
            "description": "A button mounted on the steering wheel to control audio and hands-free devices. This is a convenient feature to operate.",
            "group": false,
            "optionTitle": "Steering wheel remote control",
            "groupOptionName": "Steering wheel remote control",
            "location": "You can see that the switch is mounted on the steering wheel.",
            "subOptions": null,
            "icon": "Radio"
        },
        {
            "optionCd": "030",
            "optionName": "ECM room mirror",
            "optionTypeCd": "01",
            "sort": 13,
            "imagePath": "/carsdata/option_images/option1-12.png",
            "description": "This is a device that eliminates the glare to the driver when driving at night due to the headlights of the vehicle behind through the room mirror.",
            "group": false,
            "optionTitle": "ECM room mirror",
            "groupOptionName": "ECM room mirror",
            "location": "This is a feature that automatically prevents glare with a sensor in the mirror. You can see a circular sensor at the top center of the room mirror, and the frameless Please note that some rearview mirrors are also released, so it may be difficult to check them in normal times.",
            "subOptions": null,
            "icon": "SquareUser"
        },
        {
            "optionCd": "074",
            "optionName": "Hi-pass",
            "optionTypeCd": "01",
            "sort": 14,
            "imagePath": "/carsdata/option_images/option1-13.png",
            "description": "This is a system in which tolls are automatically paid with a card built into the Hi-pass terminal when exiting a Euro motorway tollgate.",
            "group": false,
            "optionTitle": "Hi-pass",
            "groupOptionName": "Hi-pass",
            "location": "It is often built into the rearview mirror, but the location may be different, such as on the dashboard, depending on some models or external construction methods.",
            "subOptions": null,
            "icon": "CreditCard"
        },
        {
            "optionCd": "006",
            "optionName": "Power door lock",
            "optionTypeCd": "01",
            "sort": 15,
            "imagePath": "/carsdata/option_images/option1-14.png",
            "description": "This is a function that automatically closes all doors when the door lock switch is locked on the driver's seat.",
            "group": false,
            "optionTitle": "Power door lock",
            "groupOptionName": "Power door lock",
            "location": "Located near the left window switch on the driver's seat, you can see that all doors can be opened and closed with the switch. Please note that some vehicle models do not have a locking or unlocking function when driving at a certain speed or when stopped.",
            "subOptions": null,
            "icon": "Lock"
        },
        {
            "optionCd": "008",
            "optionName": "Power steering Wheel",
            "optionTypeCd": "01",
            "sort": 16,
            "imagePath": "/carsdata/option_images/option1-15.png",
            "description": "This is a function that helps to steer easily by supplementing other power when turning the steering wheel. In the past, hydraulic power was used, but recently, the trend is to use electric power.",
            "group": false,
            "optionTitle": "Power steering wheel",
            "groupOptionName": "Power steering wheel",
            "location": "If you can turn the steering wheel without effort when the vehicle is stopped, you can determine that it is a power steering wheel. Except for some models such as Damas, it is equipped on most vehicles, unless it is an old model.",
            "subOptions": null,
            "icon": "SteeringWheel"
        },
        {
            "optionCd": "007",
            "optionName": "Power Windows",
            "optionTypeCd": "01",
            "sort": 17,
            "imagePath": "/carsdata/option_images/option1-16.png",
            "description": "This is a function that allows you to easily open and close the glass window attached to the door with a switch.",
            "group": false,
            "optionTitle": "Power Window",
            "groupOptionName": "Power Window",
            "location": "There is a switch installed on the inside of the door. Some vehicles have only this, and in the case of advanced options, there are vehicles that can be raised and lowered with one touch. If the window can be moved with a switch, check if it is a power window.",
            "subOptions": null,
            "icon": "Window"
        },
        {
            "optionCd": "002",
            "optionName": "Airbag",
            "optionTypeCd": "02",
            "sort": 18,
            "imagePath": "/carsdata/option_images/option2-1.png",
            "description": "This is a device that protects car passengers from impact in the event of a car collision. It is a representative passenger protection device along with the seat belt.",
            "group": true,
            "optionTitle": "Airbag (driver's seat, passenger's seat)",
            "groupOptionName": "Airbag",
            "location": "It is a device that protects car passengers from impact in the event of a car collision, and it is a representative passenger protection device along with the seat belt.",
            "icon": "LifeBuoy",
            "subOptions": [
                {
                    "optionCd": "026",
                    "optionName": "Airbag (driver's seat)",
                    "optionTypeCd": "02",
                    "sort": 18,
                    "imagePath": "/carsdata/option_images/option2-1.png",
                    "description": "It is a device that protects car passengers from impact in the event of a car collision, and it is a representative passenger protection device along with the seat belt.",
                    "group": false,
                    "optionTitle": "Airbag (driver's seat, passenger's seat)",
                    "groupOptionName": "Airbag (driver's seat)",
                    "location": "For the driver's seat, you can see the phrase \"airbag installed\" in the center of the steering wheel, and for the passenger seat, You can check the text on the dashboard.",
                    "subOptions": null,
                    "icon": "User"
                },
                {
                    "optionCd": "027",
                    "optionName": "Airbag (Passenger seat)",
                    "optionTypeCd": "02",
                    "sort": 19,
                    "imagePath": "/carsdata/option_images/option2-1.png",
                    "description": "It is a device that protects car passengers from impact in the event of a car collision, and is a representative passenger protection device along with a seat belt.",
                    "group": false,
                    "optionTitle": "Airbag (driver's seat, passenger's seat)",
                    "groupOptionName": "Airbag (passenger's seat)",
                    "location": "For the driver's seat, you can see the words \"Airbag installed\" in the center of the steering wheel, and for the passenger's seat, you can see the words \"Airbag installed\" on the dashboard.",
                    "subOptions": null,
                    "icon": "User"
                }
            ]
        },
        {
            "optionCd": "020",
            "optionName": "Airbag (side)",
            "optionTypeCd": "02",
            "sort": 20,
            "imagePath": "/carsdata/option_images/option2-2.png",
            "description": "It is a side airbag installed on the driver's seat and passenger's seat to protect the side of the passenger when the vehicle collides. It is an airbag.",
            "group": false,
            "optionTitle": "Airbag (side)",
            "groupOptionName": "Airbag (side)",
            "location": "It is installed on the outer seat of the driver's seat and passenger's seat, and can be confirmed by the text. Depending on the model, the rear seat side airbag may be installed separately.",
            "subOptions": null,
            "icon": "Shield"
        },
        {
            "optionCd": "056",
            "optionName": "Airbag (curtain)",
            "optionTypeCd": "02",
            "sort": 21,
            "imagePath": "/carsdata/option_images/option2-3.png",
            "description": "It is a curtain airbag that extends along the window to protect the head of the passenger in the event of a side collision of the vehicle.",
            "group": false,
            "optionTitle": "Airbag (curtain)",
            "groupOptionName": "Airbag (curtain)",
            "location": "It is usually installed on the inside pillar of the vehicle, and the airbag text is engraved on the pillar. There is.",
            "subOptions": null,
            "icon": "AlignVerticalSpaceAround"
        },
        {
            "optionCd": "001",
            "optionName": "Anti-lock brakes (ABS)",
            "optionTypeCd": "02",
            "sort": 22,
            "imagePath": "/carsdata/option_images/option2-4.png",
            "description": "This is a braking system that prevents the driver from being unable to properly control the direction of the vehicle due to the wheels locking during sudden braking and skidding or sliding to the side.",
            "group": false,
            "optionTitle": "Anti-lock brakes (ABS)",
            "groupOptionName": "Anti-lock brakes (ABS)",
            "location": "The ABS module can be checked inside the engine room, and the ABS warning light on the instrument panel can be checked when the KEY is turned ON before starting the engine.",
            "subOptions": null,
            "icon": "Activity"
        },
        {
            "optionCd": "019",
            "optionName": "Slip Anti-slip (TCS)",
            "optionTypeCd": "02",
            "sort": 23,
            "imagePath": "/carsdata/option_images/option2-5.png",
            "description": "This is a system that controls the driving force of the vehicle to prevent the tires from spinning when starting and accelerating on a slippery road.",
            "group": false,
            "optionTitle": "Anti-slip (TCS)",
            "groupOptionName": "Anti-slip (TCS)",
            "location": "The TCS module is difficult to identify, but can be checked with the TCS switch around the driver's seat, and can also be checked with the warning light or setting function on the instrument panel.",
            "subOptions": null,
            "icon": "RotateCcw"
        },
        {
            "optionCd": "055",
            "optionName": "Vehicle attitude Control device (ESC)",
            "optionTypeCd": "02",
            "sort": 24,
            "imagePath": "/carsdata/option_images/option2-6.png",
            "description": "ABS and TCS are safety devices for moving forward/backward, while ESC controls the vehicle when understeer or oversteer occurs during sharp turns.Each manufacturer has different names, but they all mean similar things. They use various names such as ESP, VDC, DSC, etc. ",
            "group": false,
            "optionTitle": "Electronic Stability Control (ESC)",
            "groupOptionName": "Electronic Stability Control (ESC)",
            "location": "You can check it on the switch around the driver's seat or on the instrument panel. It became mandatory for passenger cars and completely new cars weighing 4.5 tons or less to be installed in January 2012, and vehicles produced or modified before January were required to be installed in July 2014.",
            "subOptions": null,
            "icon": "RefreshCcw"
        },
        {
            "optionCd": "033",
            "optionName": "Tire Pressure Sensor (TPMS)",
            "optionTypeCd": "02",
            "sort": 25,
            "imagePath": "/carsdata/option_images/option2-7.png",
            "description": "It is a sensor that measures the air pressure in the four wheels of a vehicle and provides a warning to the driver. Since 2013, it has been mandatory for new car models, including passenger cars and vehicles weighing 3.5 tons or less, and all new cars released from January 2015 are required to be equipped with TPMS.",
            "group": false,
            "optionTitle": "Tire Pressure Sensor (TPMS)",
            "groupOptionName": "Tire Pressure Sensor (TPMS)",
            "location": "There is a sensor inside the tire, but it is often difficult to check with the naked eye. You can check it by looking at the TPMS warning light on the instrument panel.",
            "subOptions": null,
            "icon": "Gauge"
        },
        {
            "optionCd": "088",
            "optionName": "Lane Departure Warning System (LDWS)",
            "optionTypeCd": "02",
            "sort": 26,
            "imagePath": "/carsdata/option_images/option2-8.png",
            "description": "If the lane is deviated without a turn signal, the driver is notified with a warning sound and traffic lights, and in some models, the steering wheel may vibrate to notify the driver.",
            "group": false,
            "optionTitle": "Lane Departure Warning System (LDWS)",
            "groupOptionName": "Lane Departure Warning System (LDWS)",
            "location": "You can check it on the switch around the driver's seat or on the instrument panel. A radar is attached to the windshield behind the rearview mirror, and depending on the specifications, some vehicles only flash a warning signal or give a warning sound, while others have a function that forcibly maintains the lane or warns with vibrations on the steering wheel. In cases where basic warning signals or warning sounds are generated, it is checked as an option. ",
            "subOptions": null,
            "icon": "ArrowLeftRight"
        },
        {
            "optionCd": "002",
            "optionName": "Electronically Controlled Suspension (ECS)",
            "optionTypeCd": "02",
            "sort": 27,
            "imagePath": "/carsdata/option_images/option2-9.png",
            "description": "This is a device that automatically adjusts driving safety and riding comfort by adjusting the height or damping force of the vehicle based on input from the computer according to the driving environment. Types include electronically controlled air suspension, active damper suspension, and active preview suspension.",
            "group": false,
            "optionTitle": "Electronically Controlled Suspension (ECS)",
            "groupOptionName": "Electronically Controlled Suspension (ECS)",
            "location": "It operates through many parts such as the structure and sensors of the shock absorber, but it is difficult to confirm with the naked eye. Depending on the vehicle model, some vehicles have a switch, and the electronically controlled suspension has the function of adjusting the damping force of the suspension and the function of adjusting the height. If one of the two functions is satisfied, it is checked as an electronically controlled suspension option. ",
            "subOptions": null,
            "icon": "Sliders"
        },
        {
            "optionCd": "003",
            "optionName": "Parking detection sensor",
            "optionTypeCd": "02",
            "sort": 28,
            "imagePath": "/carsdata/option_images/option2-10.png",
            "description": "This is a system that detects obstacles with sensors installed in the front and rear bumpers when parking or driving slowly and notifies the driver with a warning sound or monitor.",
            "group": true,
            "optionTitle": "Parking detection sensor (front, rear)",
            "groupOptionName": "Parking detection sensor",
            "location": "This is a system that detects obstacles with sensors installed in the front and rear bumpers when parking or driving slowly and notifies the driver with a warning sound or monitor. It is a system.",
            "icon": "Radar",
            "subOptions": [
                {
                    "optionCd": "085",
                    "optionName": "Parking detection sensor (front)",
                    "optionTypeCd": "02",
                    "sort": 28,
                    "imagePath": "/carsdata/option_images/option2-10.png",
                    "description": "It is a system that detects obstacles with sensors installed on the front and rear bumpers when parking or driving slowly and notifies the driver with a warning sound or monitor.",
                    "group": false,
                    "optionTitle": "Parking detection sensor (front, rear)",
                    "groupOptionName": "Parking detection sensor (front)",
                    "location": "Two to four sensors are usually installed on the vehicle bumper, making it difficult to check with the naked eye. It is possible.",
                    "subOptions": null,
                    "icon": "ScanSearch"
                },
                {
                    "optionCd": "032",
                    "optionName": "Parking detection sensor (rear)",
                    "optionTypeCd": "02",
                    "sort": 29,
                    "imagePath": "/carsdata/option_images/option2-10.png",
                    "description": "It is a system that detects obstacles with sensors installed on the front and rear bumpers when parking or driving slowly and notifies the driver with a warning sound or monitor.",
                    "group": false,
                    "optionTitle": "Parking detection sensor (front, rear)",
                    "groupOptionName": "Parking detection sensor (rear)",
                    "location": "Two to four sensors are usually installed on the vehicle bumper, so they can be checked with the naked eye.",
                    "subOptions": null,
                    "icon": "ScanSearch"
                }
            ]
        },
        {
            "optionCd": "086",
            "optionName": "Rear side warning system",
            "optionTypeCd": "02",
            "sort": 30,
            "imagePath": "/carsdata/option_images/option2-11.png",
            "description": "This is a function that detects vehicles approaching from the rear side (blind spot) when changing lanes while driving and notifies the driver.",
            "group": false,
            "optionTitle": "Rear side warning system",
            "groupOptionName": "Rear side warning system",
            "location": "There is a rear side warning icon on the side mirror, and in some cases, there is a switch near the driver's seat.",
            "subOptions": null,
            "icon": "AlertTriangle"
        },
        {
            "optionCd": "058",
            "optionName": "Rear camera",
            "optionTypeCd": "02",
            "sort": 31,
            "imagePath": "/carsdata/option_images/option2-12.png",
            "description": "A camera is installed in the trunk or around the license plate to assist with parking and This is a function that allows you to check the rear through the monitor when reversing. ",
            "group": false,
            "optionTitle": "Rear camera",
            "groupOptionName": "Rear camera",
            "location": "When the reverse gear is in the R position, you can check it on the monitor located on the center fascia or the rearview mirror.",
            "subOptions": null,
            "icon": "Camera"
        },
        {
            "optionCd": "087",
            "optionName": "360-degree around view",
            "optionTypeCd": "02",
            "sort": 32,
            "imagePath": "/carsdata/option_images/option2-13.png",
            "description": "This is a function that shows the area around the vehicle on a 360-degree monitor when parking or driving slowly forward. It is a function that helps you recognize the space easily and conveniently park or drive in narrow spaces.",
            "group": false,
            "optionTitle": "360-degree around view",
            "groupOptionName": "360-degree around view",
            "location": "Vehicle Cameras are installed on the outside, and the view can be checked on the monitor. In some car models, the screen is displayed except for the front lights. ",
            "subOptions": null,
            "icon": "Globe"
        },
        {
            "optionCd": "004",
            "optionName": "Cruise Control",
            "optionTypeCd": "03",
            "sort": 33,
            "imagePath": "/carsdata/option_images/option3-1.png",
            "description": "This is a device that maintains the speed without the driver stepping on the pedal when the driver sets the speed. Adaptive is an additional function of the existing cruise control. It sets the speed and distance from the car in front, and automatically reduces the speed when the car in front reduces the speed.",
            "group": true,
            "optionTitle": "Cruise Control (General, Adaptive)",
            "groupOptionName": "Cruise Control",
            "location": "This is a device that maintains the speed without the driver stepping on the pedal when the driver sets the speed. Adaptive is an additional function of the existing cruise control. It sets the speed and distance from the car in front, and automatically reduces the speed when the car in front reduces the speed. This is a function that automatically reduces the speed when the car in front reduces the speed.",
            "icon": "GaugeCircle",
            "subOptions": [
                {
                    "optionCd": "068",
                    "optionName": "Cruise Control (General)",
                    "optionTypeCd": "03",
                    "sort": 33,
                    "imagePath": "/carsdata/option_images/option3-1.png",
                    "description": "This is a device that maintains the speed without the driver stepping on the pedal when the driver sets the speed. Adaptive is an additional function of the existing cruise control. It sets the speed and distance from the car in front, and automatically reduces the speed when the car in front reduces the speed.",
                    "group": false,
                    "optionTitle": "Cruise Control (General, Adaptive)",
                    "groupOptionName": "Cruise Control (General)",
                    "location": "Cruise control can be checked with a switch around the steering wheel, and adaptive applies radar to the front of the vehicle and can be checked with the instrument panel settings. Adaptive is a function that basically sets the distance between cars and adjusts the speed. Check it out as an option.",
                    "subOptions": null,
                    "icon": "GaugeCircle"
                },
                {
                    "optionCd": "079",
                    "optionName": "Cruise Control (Adaptive)",
                    "optionTypeCd": "03",
                    "sort": 34,
                    "imagePath": "/carsdata/option_images/option3-1.png",
                    "description": "This is a device that maintains the speed set by the driver without the driver stepping on the pedal. Adaptive is an additional function of the existing cruise control. It sets the speed and distance from the car in front, and automatically reduces the speed when the car in front reduces its speed.",
                    "group": false,
                    "optionTitle": "Cruise Control (Normal, Adaptive)",
                    "groupOptionName": "Cruise Control (Adaptive)",
                    "location": "Cruise control can be checked with a switch around the steering wheel, and adaptive uses a radar on the front of the vehicle and can be checked with the instrument panel settings. Adaptive basically sets the distance between vehicles and adjusts the speed as an option.",
                    "subOptions": null,
                    "icon": "GaugeCircle"
                }
            ]
        },
        {
            "optionCd": "095",
            "optionName": "Head-up Display (HUD)",
            "optionTypeCd": "03",
            "sort": 35,
            "imagePath": "/carsdata/option_images/option3-2.png",
            "description": "This is a function that projects vehicle information on the driver's windshield so that the driver can easily check the information (speed, navigation). ",
            "group": false,
            "optionTitle": "Head-up Display (HUD)",
            "groupOptionName": "Head-up Display (HUD)",
            "location": "There is a device that can project the display onto the glass on the dashboard in front of the driver's seat so that you can check it with your eyes, and some vehicles have a switch around the driver's seat.",
            "subOptions": null,
            "icon": "MonitorUp"
        },
        {
            "optionCd": "094",
            "optionName": "Electronic Parking Brake (EPB)",
            "optionTypeCd": "03",
            "sort": 36,
            "imagePath": "/carsdata/option_images/option3-3.png",
            "description": "After parking the vehicle, this function allows you to easily operate the parking brake with your fingers without having to lock it with your hands or feet. It also automatically releases the brake, preventing you from driving with the parking brake locked.",
            "group": false,
            "optionTitle": "Electronic Parking Brake (EPB)",
            "groupOptionName": "Electronic Parking Brake (EPB)",
            "location": "Located near the driver's seat or transmission and has a switch It operates in this way.",
            "subOptions": null,
            "icon": "SquareParking"
        },
        {
            "optionCd": "023",
            "optionName": "Automatic Air Conditioning",
            "optionTypeCd": "03",
            "sort": 37,
            "imagePath": "/carsdata/option_images/option3-4.png",
            "description": "This is an air conditioner that automatically adjusts the wind speed and temperature when the user sets the desired temperature to maintain a constant temperature. In the case of dual full auto air conditioners, the temperature of the passenger seat can be adjusted independently.",
            "group": false,
            "optionTitle": "Automatic Air Conditioning",
            "groupOptionName": "Automatic Air Conditioning",
            "location": "The air conditioning system is located on the center fascia, and the AUTO button There is.",
            "subOptions": null,
            "icon": "Thermometer"
        },
        {
            "optionCd": "057",
            "optionName": "Smart Key",
            "optionTypeCd": "03",
            "sort": 38,
            "imagePath": "/carsdata/option_images/option3-5.png",
            "description": "It is a convenient device that allows you to unlock the door or start the car by pressing a button just by carrying the smart key.",
            "group": false,
            "optionTitle": "Smart Key",
            "groupOptionName": "Smart Key",
            "location": "The smart key does not have a key shape in appearance and has a function that allows you to open the door (KEYLESS ENTRY) or start the car (KEYLESS GO) by carrying the smart key. If one of the two functions is satisfied, it is checked as an option of the smart key.",
            "subOptions": null,
            "icon": "KeyRound"
        },
        {
            "optionCd": "015",
            "optionName": "Wireless Door Locking device",
            "optionTypeCd": "03",
            "sort": 39,
            "imagePath": "/carsdata/option_images/option3-6.png",
            "description": "This is a convenient device that allows you to lock/unlock the vehicle with a wireless remote control without inserting the key into the door.",
            "group": false,
            "optionTitle": "Wireless Door Lock",
            "groupOptionName": "Wireless Door Lock",
            "location": "The car key has a lock/unlock remote control button attached to it or there is a remote control with the key.",
            "subOptions": null,
            "icon": "Wifi"
        },
        {
            "optionCd": "081",
            "optionName": "Rain Sensor",
            "optionTypeCd": "03",
            "sort": 40,
            "imagePath": "/carsdata/option_images/option3-7.png",
            "description": "The wiper automatically wipes the water from the windshield when it detects rainwater falling on the windshield. The wiper speed is also automatically adjusted depending on the amount of rain.",
            "group": false,
            "optionTitle": "Rain Sensor",
            "groupOptionName": "Rain Sensor",
            "location": "You can check it on the wiper control switch around the steering wheel. There is an AUTO button and a detection sensor on the top of the windshield. ",
            "subOptions": null,
            "icon": "CloudRain"
        },
        {
            "optionCd": "097",
            "optionName": "Auto Light",
            "optionTypeCd": "03",
            "sort": 41,
            "imagePath": "/carsdata/option_images/option3-8.png",
            "description": "This is a function that automatically turns the vehicle's lights on and off by detecting darkness in tunnels or surroundings without having to manually operate them.",
            "group": false,
            "optionTitle": "Auto Light",
            "groupOptionName": "Auto Light",
            "location": "You can check it on the headlamp control switch around the steering wheel. There is an AUTO button and a detection sensor on the front of the dashboard. There is.",
            "subOptions": null,
            "icon": "Lightbulb"
        },
        {
            "optionCd": "005",
            "optionName": "Curtain/Blind",
            "optionTypeCd": "03",
            "sort": 42,
            "imagePath": "/carsdata/option_images/option3-9.png",
            "description": "Curtain/Blind that blocks sunlight.",
            "group": true,
            "optionTitle": "Curtain/Blind (Rear seat, Rear)",
            "groupOptionName": "Curtain/Blind",
            "location": "Curtain/Blind that blocks sunlight It is a curtain/blind.",
            "icon": "Window",
            "subOptions": [
                {
                    "optionCd": "092",
                    "optionName": "Curtain/blind (rear seat)",
                    "optionTypeCd": "03",
                    "sort": 42,
                    "imagePath": "/carsdata/option_images/option3-9.png",
                    "description": "It is a curtain/blind that blocks sunlight.",
                    "group": false,
                    "optionTitle": "Curtain/blind (rear seat, rear)",
                    "groupOptionName": "Curtain/blind (rear seat)",
                    "location": "There is a device that can manually/automatically close the curtain around the rear seat door window. If it is automatic, there is a switch around the door. In the rear, there is a device that can manually/automatically close the curtain towards the rear window. If it is automatic, there is a switch for moving the curtain forward/backward. There is.",
                    "subOptions": null,
                    "icon": "Window"
                },
                {
                    "optionCd": "093",
                    "optionName": "Curtain/Blind (Rear)",
                    "optionTypeCd": "03",
                    "sort": 43,
                    "imagePath": "/carsdata/option_images/option3-9.png",
                    "description": "Curtain/Blind that blocks sunlight.",
                    "group": false,
                    "optionTitle": "Curtain/Blind (Rear Window, Rear)",
                    "groupOptionName": "Curtain/Blind (Rear)",
                    "location": "There is a device that can manually/automatically close the curtain around the rear seat door window. If it is automatic, there is a switch around the door. In the rear, there is a device that can manually/automatically close the curtain towards the rear window. If it is automatic, there is a switch for moving the curtain forward/backward.",
                    "subOptions": null,
                    "icon": "Window"
                }
            ]
        },
        {
            "optionCd": "005",
            "optionName": "Navigation",
            "optionTypeCd": "03",
            "sort": 44,
            "imagePath": "/carsdata/option_images/option3-10.png",
            "description": "When you set a destination, the monitor with built-in GPS provides route guidance and various traffic information.",
            "group": false,
            "optionTitle": "Navigation",
            "groupOptionName": "Navigation",
            "location": "A monitor screen is mounted on the center fascia, allowing you to check the vehicle's location on the map and set a destination.",
            "subOptions": null,
            "icon": "Map"
        },
        {
            "optionCd": "004",
            "optionName": "Front seat AV Monitor",
            "optionTypeCd": "03",
            "sort": 45,
            "imagePath": "/carsdata/option_images/option3-11.png",
            "description": "A device equipped with a video system such as a TV or video inside a vehicle.",
            "group": false,
            "optionTitle": "Front seat AV monitor",
            "groupOptionName": "Front seat AV monitor",
            "location": "A monitor screen is mounted on the center fascia.",
            "subOptions": null,
            "icon": "Monitor"
        },
        {
            "optionCd": "054",
            "optionName": "Rear seat AV monitor",
            "optionTypeCd": "03",
            "sort": 46,
            "imagePath": "/carsdata/option_images/option3-12.png",
            "description": "A device equipped with a video system such as a TV or video inside a vehicle.",
            "group": false,
            "optionTitle": "Rear seat AV monitor",
            "groupOptionName": "Rear seat AV Monitor",
            "location": "It is often installed behind the front seat, and some car models are also installed on the front seat armrest, roof, etc.",
            "subOptions": null,
            "icon": "Monitor"
        },
        {
            "optionCd": "096",
            "optionName": "Bluetooth",
            "optionTypeCd": "03",
            "sort": 47,
            "imagePath": "/carsdata/option_images/option3-13.png",
            "description": "This is a function that allows you to use various files and information such as phone calls and music by wirelessly connecting your smartphone to the vehicle's Bluetooth-enabled audio.",
            "group": false,
            "optionTitle": "Bluetooth",
            "groupOptionName": "Bluetooth",
            "location": "You can check the function in the audio settings. Bluetooth has an audio streaming function that allows you to listen to music and a hands-free function that allows you to make phone calls. If one of the two functions is satisfied, check the Bluetooth option. It is normal that the function may be lost during the installation of some navigation systems, etc. Please check if it is working.",
            "subOptions": null,
            "icon": "Bluetooth"
        },
        {
            "optionCd": "003",
            "optionName": "CD Player",
            "optionTypeCd": "03",
            "sort": 48,
            "imagePath": "/carsdata/option_images/option3-14.png",
            "description": "This is a device that plays CDs containing music.",
            "group": false,
            "optionTitle": "CD Player",
            "groupOptionName": "CD Player",
            "location": "This is a player or changer that can play CDs and is located in the center fascia. In some cases, it is also installed in the console box, trunk, etc..",
            "subOptions": null,
            "icon": "Disc"
        },
        {
            "optionCd": "072",
            "optionName": "USB Terminal",
            "optionTypeCd": "03",
            "sort": 49,
            "imagePath": "/carsdata/option_images/option3-15.png",
            "description": "This terminal allows you to listen to music from portable devices such as MP3s and PMPs on the car's audio system through external input via the USB connection jack.",
            "group": false,
            "optionTitle": "USB terminal",
            "groupOptionName": "USB terminal",
            "location": "The USB terminal is usually located at the bottom of the center fascia and some console boxes.",
            "subOptions": null,
            "icon": "Usb"
        },
        {
            "optionCd": "071",
            "optionName": "AUX terminal",
            "optionTypeCd": "03",
            "sort": 50,
            "imagePath": "/carsdata/option_images/option3-16.png",
            "description": "This terminal allows you to listen to music from portable devices such as MP3s and PMPs on the car's audio system through external input via the AUX connection jack.",
            "group": false,
            "optionTitle": "AUX Terminal",
            "groupOptionName": "AUX terminal",
            "location": "The AUX terminal is mostly located at the bottom of the center fascia and some are in the console box.",
            "subOptions": null,
            "icon": "Cable"
        },
        {
            "optionCd": "014",
            "optionName": "Leather seat",
            "optionTypeCd": "04",
            "sort": 51,
            "imagePath": "/carsdata/option_images/option4-1.png",
            "description": "The seat material of the vehicle is leather, suede, and a mixture of fabric and leather. It is considered a leather seat.",
            "group": false,
            "optionTitle": "Leather seat",
            "groupOptionName": "Leather seat",
            "location": "You can see the part of the seat made of leather or a material that feels like leather rather than fabric. Depending on the specifications, there are various types such as artificial, natural, suede, and a mixture of fabric and seat.\nRegardless of the type, it is considered a leather seat. Check.",
            "subOptions": null,
            "icon": "Armchair"
        },
        {
            "optionCd": "006",
            "optionName": "Power seat",
            "optionTypeCd": "04",
            "sort": 52,
            "imagePath": "/carsdata/option_images/option4-2.png",
            "description": "This is a function that allows you to conveniently adjust the seat height, forward/backward, and backrest inclination to the desired position with a switch.",
            "group": true,
            "optionTitle": "Power seat (driver's seat, passenger's seat)",
            "groupOptionName": "Power seat",
            "location": "This is a function that allows you to conveniently adjust the seat height, forward/backward, and backrest inclination to the desired position with a switch. This is a function.",
            "icon": "MoveUpRight",
            "subOptions": [
                {
                    "optionCd": "021",
                    "optionName": "Electric seat (driver's seat)",
                    "optionTypeCd": "04",
                    "sort": 52,
                    "imagePath": "/carsdata/option_images/option4-2.png",
                    "description": "This function allows you to conveniently adjust the seat height, forward/backward movement, and backrest tilt to the desired position with a switch.",
                    "group": false,
                    "optionTitle": "Electric seat (driver's seat, passenger's seat)",
                    "groupOptionName": "Electric seat (driver's seat)",
                    "location": "There is a switch under the seat or on the door side, and some electric seats do not have some of the height, forward/backward movement, and backrest functions. If one of the three functions is satisfied,\nit is selected as an electric seat option. Check.",
                    "subOptions": null,
                    "icon": "MoveUpRight"
                },
                {
                    "optionCd": "035",
                    "optionName": "Electric seat (passenger seat)",
                    "optionTypeCd": "04",
                    "sort": 53,
                    "imagePath": "/carsdata/option_images/option4-2.png",
                    "description": "This is a function that allows you to conveniently adjust the seat height, forward/backward, and backrest incline to the desired position with a switch.",
                    "group": false,
                    "optionTitle": "Electric seat (driver's seat, passenger's seat)",
                    "groupOptionName": "Electric seat (passenger's seat)",
                    "location": "There is a switch under the seat or on the door, and some electric seats do not have some of the functions of height, front/back, and backrest. If one of the three functions is satisfied,\ncheck with the electric seat option. ",
                    "subOptions": null,
                    "icon": "MoveUpRight"
                }
            ]
        },
        {
            "optionCd": "089",
            "optionName": "Electric seat (rear seat)",
            "optionTypeCd": "04",
            "sort": 54,
            "imagePath": "/carsdata/option_images/option4-3.png",
            "description": "Usually found in large vehicles, you can conveniently adjust the seat height, front/back, and backrest incline to the desired position with a switch. This is a function that warms the seats by turning the switch ON/OFF in winter.",
            "group": false,
            "optionTitle": "Power seat (rear seat)",
            "groupOptionName": "Power seat (rear seat)",
            "location": "You can check the switch on the rear seat door or center armrest. Vehicles that control folding with an electric switch, such as SUVs, can also be considered rear seat power seats.",
            "subOptions": null,
            "icon": "MoveUpRight"
        },
        {
            "optionCd": "007",
            "optionName": "Heated seat",
            "optionTypeCd": "04",
            "sort": 55,
            "imagePath": "/carsdata/option_images/option4-4.png",
            "description": "This is a function that warms the seats by turning the switch ON/OFF in winter.",
            "group": true,
            "optionTitle": "Heated seat (front seat, rear seat)",
            "groupOptionName": "Heated seat",
            "location": "This is a function that warms the seats by turning the switch ON/OFF in winter. This is a function.",
            "icon": "Flame",
            "subOptions": [
                {
                    "optionCd": "022",
                    "optionName": "Heated seats (front seats)",
                    "optionTypeCd": "04",
                    "sort": 55,
                    "imagePath": "/carsdata/option_images/option4-4.png",
                    "description": "This is a function that warms the seats by turning the switch ON/OFF in winter.",
                    "group": false,
                    "optionTitle": "Heated seats (front seats, rear seats)",
                    "groupOptionName": "Heated seats (front seats)",
                    "location": "The front seats are located around the transmission or center fascia, and the rear seats are located around the rear door window switch, rear air vent, or rear armrest. When the switch is operated,\nthe seats It gets warm.",
                    "subOptions": null,
                    "icon": "Flame"
                },
                {
                    "optionCd": "063",
                    "optionName": "Heated seats (rear seats)",
                    "optionTypeCd": "04",
                    "sort": 56,
                    "imagePath": "/carsdata/option_images/option4-4.png",
                    "description": "This is a function that warms the seats by turning the switch ON/OFF in winter.",
                    "group": false,
                    "optionTitle": "Heated seats (front seats, rear seats)",
                    "groupOptionName": "Heated seats (rear seats)",
                    "location": "The front seats are located around the transmission or center fascia, and the rear seats are located around the rear door window switch, rear air vent, or rear armrest. When the switch is operated,\nthe seats get warm.",
                    "subOptions": null,
                    "icon": "Flame"
                }
            ]
        },
        {
            "optionCd": "008",
            "optionName": "Memory Seat",
            "optionTypeCd": "04",
            "sort": 57,
            "imagePath": "/carsdata/option_images/option4-5.png",
            "description": "This is a function that allows you to easily adjust the seat to a comfortable position on the driver's seat and passenger's seat by setting it to remember that position and then adjusting it to that position with a button. It can also be used conveniently when another driver has adjusted the seat position differently. ",
            "group": true,
            "optionTitle": "Memory Seat (Driver's Seat, Passenger's Seat)",
            "groupOptionName": "Memory Seat",
            "location": "This is a function that allows you to easily adjust the seat to that position with a button by fixing the seat in a comfortable position on the driver's seat and passenger's seat and setting it to remember that position. It can be used conveniently when another driver has adjusted the seat position differently. ",
            "icon": "Save",
            "subOptions": [
                {
                    "optionCd": "051",
                    "optionName": "Memory Seat (Driver's Seat)",
                    "optionTypeCd": "04",
                    "sort": 57,
                    "imagePath": "/carsdata/option_images/option4-5.png",
                    "description": "This is a function that allows you to easily adjust the seat to that position with a button by fixing the seat in a comfortable position on the driver's seat and passenger's seat and setting it to remember that position. It can be used conveniently when another driver has adjusted the seat position differently. ",
                    "group": false,
                    "optionTitle": "Memory Seat (Driver's Seat, Passenger's Seat)",
                    "groupOptionName": "Memory Seat (driver's seat)",
                    "location": "Located on the door trim or under the seat, and when you set it and specify a number, the contents of the adjusted seat are saved.",
                    "subOptions": null,
                    "icon": "Save"
                },
                {
                    "optionCd": "078",
                    "optionName": "Memory seat (passenger's seat)",
                    "optionTypeCd": "04",
                    "sort": 58,
                    "imagePath": "/carsdata/option_images/option4-5.png",
                    "description": "This function allows you to fix the seat in a comfortable position on the driver's seat and passenger's seat and set it to remember that position, and then easily adjust it to that position with a button. It can also be conveniently used when another driver has adjusted the seat position differently. ",
                    "group": false,
                    "optionTitle": "Memory seat (driver's seat, passenger's seat)",
                    "groupOptionName": "Memory seat (passenger's seat)",
                    "location": "Located on the door trim or under the seat, and when you set it and specify a number, the contents of the adjusted seat are saved. Saved.",
                    "subOptions": null,
                    "icon": "Save"
                }
            ]
        },
        {
            "optionCd": "009",
            "optionName": "Ventilated seat",
            "optionTypeCd": "04",
            "sort": 59,
            "imagePath": "/carsdata/option_images/option4-6.png",
            "description": "In hot weather, by operating the ventilation seat switch, cool air is circulated in the seat to remove heat and keep you comfortable. ",
            "group": true,
            "optionTitle": "Ventilated seat (driver's seat, passenger's seat)",
            "groupOptionName": "Ventilated seat",
            "location": "In hot weather, by operating the ventilation seat switch, cool air is circulated in the seat to remove heat and keep you comfortable. ",
            "icon": "Wind",
            "subOptions": [
                {
                    "optionCd": "034",
                    "optionName": "Ventilated seat (driver's seat)",
                    "optionTypeCd": "04",
                    "sort": 59,
                    "imagePath": "/carsdata/option_images/option4-6.png",
                    "description": "In hot weather, by operating the ventilation seat switch, cool air is circulated in the seat to remove heat and maintain comfort in the buttocks area that is not touched by the air conditioner.",
                    "group": false,
                    "optionTitle": "Ventilated seat (driver's seat, passenger's seat)",
                    "groupOptionName": "Ventilated seat (driver's seat)",
                    "location": "Located around the transmission or center fascia, when the switch is operated, cool air is circulated. I can feel it.",
                    "subOptions": null,
                    "icon": "Wind"
                },
                {
                    "optionCd": "077",
                    "optionName": "Ventilated seat (passenger seat)",
                    "optionTypeCd": "04",
                    "sort": 60,
                    "imagePath": "/carsdata/option_images/option4-6.png",
                    "description": "In hot weather, by operating the ventilation seat switch, cool air is circulated in the seat to remove heat and maintain comfort in the buttocks area that is not touched by the air conditioner.",
                    "group": false,
                    "optionTitle": "Ventilated seat (driver's seat, passenger seat)",
                    "groupOptionName": "Ventilated seat (passenger seat)",
                    "location": "Located around the transmission or center fascia, and cool air is felt when the switch is operated.",
                    "subOptions": null,
                    "icon": "Wind"
                }
            ]
        },
        {
            "optionCd": "090",
            "optionName": "Ventilated seat (rear seat)",
            "optionTypeCd": "04",
            "sort": 61,
            "imagePath": "/carsdata/option_images/option4-7.png",
            "description": "There is a separate ventilation seat function in the rear seat. In hot weather, by operating the ventilation seat switch, cool air is circulated in the seat to control the heat and maintain comfort. ",
            "group": false,
            "optionTitle": "Ventilated seat (rear seat)",
            "groupOptionName": "Ventilated seat (rear seat)",
            "location": "Located around the rear door window switch, rear air vent, and rear armrest, and cool air is felt when the switch is operated. It is felt.",
            "subOptions": null,
            "icon": "Wind"
        },
        {
            "optionCd": "091",
            "optionName": "Massage seat",
            "optionTypeCd": "04",
            "sort": 62,
            "imagePath": "/carsdata/option_images/option4-8.png",
            "description": "Also called a massage seat, it is a function that adds a massage function to the car seat to relieve fatigue.",
            "group": false,
            "optionTitle": "Massage seat",
            "groupOptionName": "Massage seat",
            "location": "The function is available in all or part of the front or rear seats, and when the switch is operated, you can tell whether the massage is operating toward the backrest by the air tube on the seat. ",
            "subOptions": null,
            "icon": "Vibrate"
        }
    ]
}
